[tool.poetry]
name = "DogeSetup"
version = "1.0"
description = "ğŸ¶ Easy to install the Doge UserBot for Telegram. ğŸ¾"
authors = ["DogeUserBot <DogeUserBot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
DogeSetup = "^0.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"